application:
  name: dev环境 spring-boot-properties
  version: dev环境 1.0-SNAPSHOT
developer:
  name: dev环境 xkcoding
  website: dev环境 http://jiyong.me
  qq: dev环境 123456787
  phone-number: dev环境 12345678
